// Command gen-eas-codepages converts the protocol tag tables from the
// reference ActiveSync implementation (activesync-go codepages, facts from
// [MS-ASWBXML]) into a self-contained Go data file for the mailez EAS
// server. Run once during development; the output is committed.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var (
	nsRe  = regexp.MustCompile(`NS_(\w+)\s+(?:string\s+)?=\s*"([^"]+)"`)
	cpRe  = regexp.MustCompile(`CP_(\w+)\s+byte\s*=\s*(\d+)`)
	tagRe = regexp.MustCompile(`TAG_(\w+)\s+string\s*=\s*"([^"]+)"`)
	idRe  = regexp.MustCompile(`ID_(\w+)\s+byte\s*=\s*(0x[0-9A-Fa-f]+)`)
	addRe = regexp.MustCompile(`AddTag\(TAG_(\w+),\s*ID_(\w+)\)`)
)

type cp struct {
	ns      string
	index   int
	tags    map[string]string // tag name -> id constant (token in hex)
	order   []string
	guarded bool // tags added only for newer protocol versions
}

func main() {
	srcDir := os.Args[1]
	outFile := os.Args[2]
	files, err := filepath.Glob(filepath.Join(srcDir, "*.go"))
	if err != nil {
		panic(err)
	}
	sort.Strings(files)
	var cps []*cp
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			panic(err)
		}
		src := stripComments(string(b))
		nsm := nsRe.FindStringSubmatch(src)
		if nsm == nil {
			continue
		}
		cpm := cpRe.FindStringSubmatch(src)
		if cpm == nil {
			continue
		}
		idx, _ := strconv.Atoi(cpm[2])
		c := &cp{ns: nsm[2], index: idx, tags: map[string]string{}}
		tagIDs := map[string]string{}
		for _, m := range tagRe.FindAllStringSubmatch(src, -1) {
			tagIDs[m[1]] = m[2]
		}
		for _, m := range idRe.FindAllStringSubmatch(src, -1) {
			tagIDs["ID_"+m[1]] = m[2]
		}
		for _, m := range addRe.FindAllStringSubmatch(src, -1) {
			id, ok := tagIDs["ID_"+m[2]]
			if !ok {
				panic(fmt.Sprintf("%s: missing id for %s", f, m[2]))
			}
			tagName := tagIDs[m[1]]
			if tagName == "" {
				panic(fmt.Sprintf("%s: missing tag name for %s", f, m[1]))
			}
			c.tags[tagName] = id
			c.order = append(c.order, tagName)
		}
		// The AirSync/Email/Calendar codepages guard a few 14.x tags; we
		// emit them all so the 14.1 codebook is complete.
		c.guarded = strings.Contains(src, "protocolVersion >")
		cps = append(cps, c)
	}
	sort.Slice(cps, func(i, j int) bool { return cps[i].index < cps[j].index })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/gen-eas-codepages; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Tag tables per [MS-ASWBXML] (Exchange ActiveSync WBXML code pages).\n\n")
	fmt.Fprintf(&b, "package activesync\n\n")
	fmt.Fprintf(&b, "import (\n\t\"strconv\"\n\t\"strings\"\n)\n\n")
	fmt.Fprintf(&b, "type codePageDef struct {\n\tindex   byte\n\tns      string\n\tbyName  map[string]byte\n\tbyToken map[byte]string\n}\n\n")
	fmt.Fprintf(&b, "func newCodePageDef(index byte, ns string, pairs [][2]string) *codePageDef {\n")
	fmt.Fprintf(&b, "\tcp := &codePageDef{index: index, ns: ns, byName: map[string]byte{}, byToken: map[byte]string{}}\n")
	fmt.Fprintf(&b, "\tfor _, p := range pairs {\n\t\ttok, _ := strconv.ParseUint(strings.TrimPrefix(p[1], \"0x\"), 16, 8)\n")
	fmt.Fprintf(&b, "\t\tcp.byName[p[0]] = byte(tok)\n\t\tcp.byToken[byte(tok)] = p[0]\n\t}\n\treturn cp\n}\n\n")
	fmt.Fprintf(&b, "var easCodePages = []*codePageDef{\n")
	for _, c := range cps {
		fmt.Fprintf(&b, "\t{index: %d, ns: %q, byName: map[string]byte{", c.index, c.ns)
		names := append([]string(nil), c.order...)
		sort.Strings(names)
		for _, n := range names {
			fmt.Fprintf(&b, "%q: 0x%s, ", n, strings.ToUpper(strings.TrimPrefix(c.tags[n], "0x")))
		}
		fmt.Fprintf(&b, "}, byToken: map[byte]string{")
		for _, n := range names {
			fmt.Fprintf(&b, "0x%s: %q, ", strings.ToUpper(strings.TrimPrefix(c.tags[n], "0x")), n)
		}
		fmt.Fprintf(&b, "}},\n")
	}
	fmt.Fprintf(&b, "}\n")
	if err := os.WriteFile(outFile, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s with %d code pages\n", outFile, len(cps))
}

// stripComments removes // line comments so commented-out constants are not
// mistaken for protocol facts.
func stripComments(src string) string {
	lines := strings.Split(src, "\n")
	for i, ln := range lines {
		if j := strings.Index(ln, "//"); j >= 0 {
			lines[i] = ln[:j]
		}
	}
	return strings.Join(lines, "\n")
}
