// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai/draft": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "Draft reply",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/ai/prioritize": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "Prioritize inbox",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/ai/search": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "AI search",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_mail.Message"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/ai/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "AI status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ai/summarize": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "Summarize email",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/aliases": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aliases"
                ],
                "summary": "List aliases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Alias"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aliases"
                ],
                "summary": "Create alias",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Alias"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/aliases/{email}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aliases"
                ],
                "summary": "Get alias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "alias address",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Alias"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "aliases"
                ],
                "summary": "Update alias",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "aliases"
                ],
                "summary": "Delete alias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "alias address",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/alternatives": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "List alternatives",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Alternative"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Create alternative",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Alternative"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/alternatives/{name}": {
            "delete": {
                "tags": [
                    "domains"
                ],
                "summary": "Delete alternative",
                "parameters": [
                    {
                        "type": "string",
                        "description": "alternative name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/anon-aliases": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aliases"
                ],
                "summary": "List anonymous aliases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Alias"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aliases"
                ],
                "summary": "Create anonymous alias",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Alias"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/anon-aliases/domains": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aliases"
                ],
                "summary": "Anonymous-alias domains",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Domain"
                            }
                        }
                    }
                }
            }
        },
        "/anon-aliases/{email}": {
            "delete": {
                "tags": [
                    "aliases"
                ],
                "summary": "Delete anonymous alias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "alias address",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/audit": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Audit log",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.AuditLog"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/config/export": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Export configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/config/import": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Import configuration",
                "responses": {
                    "200": {
                        "description": "import stats",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/contacts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contacts"
                ],
                "summary": "List contacts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Contact"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contacts"
                ],
                "summary": "Create contact",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Contact"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/contacts/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "contacts"
                ],
                "summary": "Update contact",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "contacts"
                ],
                "summary": "Delete contact",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "contact id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/domains": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "List domains",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Domain"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Create domain",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Domain"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/domains/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Get domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "domain name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Domain"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Update domain",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "domains"
                ],
                "summary": "Delete domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "domain name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/domains/{name}/dkim": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "DKIM status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "domain name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Generate DKIM key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "domain name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/domains/{name}/managers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "List domain managers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "domain name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Add domain manager",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/domains/{name}/managers/{email}": {
            "delete": {
                "tags": [
                    "domains"
                ],
                "summary": "Remove domain manager",
                "parameters": [
                    {
                        "type": "string",
                        "description": "domain name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "manager email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/fetches": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fetch"
                ],
                "summary": "List fetch accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter by user email",
                        "name": "user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Fetch"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fetch"
                ],
                "summary": "Create fetch account",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Fetch"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/fetches/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "fetch"
                ],
                "summary": "Update fetch account",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "fetch"
                ],
                "summary": "Delete fetch account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "fetch id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/mail/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Delete message",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mail/draft": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Save draft",
                "responses": {
                    "200": {
                        "description": "uid",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mail/flag": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Set message flag",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mail/folders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "List folders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/mail/identities": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Send-as identities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_alias.MailIdentity"
                            }
                        }
                    }
                }
            }
        },
        "/mail/message": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Get message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mailbox",
                        "name": "folder",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "message uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_mail.Message"
                        }
                    }
                }
            }
        },
        "/mail/messages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "List messages",
                "parameters": [
                    {
                        "type": "string",
                        "default": "INBOX",
                        "description": "mailbox name",
                        "name": "folder",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "page (0-based)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_mail.Message"
                            }
                        }
                    }
                }
            }
        },
        "/mail/move": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Move messages",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mail/pgp/decrypt": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pgp"
                ],
                "summary": "Decrypt message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/mail/pgp/encrypt": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pgp"
                ],
                "summary": "Encrypt message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/mail/pgp/sign": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pgp"
                ],
                "summary": "Sign message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/mail/pgp/verify": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pgp"
                ],
                "summary": "Verify signature",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/mail/raw": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Raw message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mailbox",
                        "name": "folder",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "message uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mail/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Search messages",
                "parameters": [
                    {
                        "type": "string",
                        "default": "INBOX",
                        "description": "mailbox or all",
                        "name": "folder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search expression",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_mail.Message"
                            }
                        }
                    }
                }
            }
        },
        "/mail/send": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Send message",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mail/thread": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Message thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mailbox",
                        "name": "folder",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "thread id",
                        "name": "thread_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mail/unseen": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mail"
                ],
                "summary": "Unseen counts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Current user settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/me/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Change password",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/me/pgp": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "PGP status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "me"
                ],
                "summary": "Delete PGP key",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/me/pgp/generate": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Generate PGP key",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/me/settings": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Update settings",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/me/totp": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "TOTP status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Disable TOTP",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/me/totp/enable": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "Enable TOTP",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pgp/key": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pgp"
                ],
                "summary": "Lookup public key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/push/subscribe": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "push"
                ],
                "summary": "Subscribe to push",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "push"
                ],
                "summary": "Unsubscribe from push",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/push/vapid": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "push"
                ],
                "summary": "VAPID public key",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/relays": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "List relays",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Relay"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Create relay",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.Relay"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/relays/{name}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Update relay",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "domains"
                ],
                "summary": "Delete relay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "relay name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/sieve": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sieve"
                ],
                "summary": "List Sieve scripts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/sieve/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sieve"
                ],
                "summary": "Get Sieve script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "sieve"
                ],
                "summary": "Save Sieve script",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "sieve"
                ],
                "summary": "Delete Sieve script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/sieve/{name}/activate": {
            "post": {
                "tags": [
                    "sieve"
                ],
                "summary": "Activate Sieve script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signup"
                ],
                "summary": "Self-register",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/signup/domains": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signup"
                ],
                "summary": "Signup domains",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Domain"
                            }
                        }
                    }
                }
            }
        },
        "/sso/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "email + password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "email",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    },
                    "429": {
                        "description": "rate_limited",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/sso/login/totp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Complete 2FA login",
                "parameters": [
                    {
                        "description": "pending_token + code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "email",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    },
                    "429": {
                        "description": "rate_limited",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/sso/logout": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/sso/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/tokens": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "List app tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.Token"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Create app token",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/tokens/{id}": {
            "delete": {
                "tags": [
                    "tokens"
                ],
                "summary": "Delete app token",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter by domain",
                        "name": "domain",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mailez_backend_internal_core_models.User"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        },
        "/users/{email}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.User"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mailez_backend_internal_core_models.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_alias.MailIdentity": {
            "type": "object",
            "properties": {
                "dkim_enabled": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "internal_auth.MeResponse": {
            "type": "object",
            "properties": {
                "displayed_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "global_admin": {
                    "type": "boolean"
                },
                "manager": {
                    "type": "boolean"
                }
            }
        },
        "internal_auth.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "pw": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "rate_limited"
                },
                "error": {
                    "type": "string",
                    "example": "something went wrong"
                }
            }
        },
        "mailez_backend_internal_core_models.Alias": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "domain_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "hostname": {
                    "description": "Anonymous Email Service metadata",
                    "type": "string"
                },
                "localpart": {
                    "type": "string"
                },
                "owner_email": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wildcard": {
                    "type": "boolean"
                }
            }
        },
        "mailez_backend_internal_core_models.Alternative": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "domain_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.AuditLog": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.Contact": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.Domain": {
            "type": "object",
            "properties": {
                "anonmail_enabled": {
                    "type": "boolean"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "max_aliases": {
                    "type": "integer"
                },
                "max_quota_bytes": {
                    "type": "integer"
                },
                "max_users": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "signup_enabled": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.Fetch": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "folders": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invisible": {
                    "type": "boolean"
                },
                "keep": {
                    "type": "boolean"
                },
                "last_check": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "scan": {
                    "type": "boolean"
                },
                "tls": {
                    "type": "boolean"
                },
                "user_email": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.Relay": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "smtp": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.Token": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_core_models.User": {
            "type": "object",
            "properties": {
                "allow_spoofing": {
                    "type": "boolean"
                },
                "blacklist": {
                    "type": "string"
                },
                "change_pw_next_login": {
                    "type": "boolean"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "displayed_name": {
                    "type": "string"
                },
                "domain_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "enable_imap": {
                    "type": "boolean"
                },
                "enable_pop": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "forward_destination": {
                    "type": "string"
                },
                "forward_enabled": {
                    "type": "boolean"
                },
                "forward_keep": {
                    "type": "boolean"
                },
                "global_admin": {
                    "type": "boolean"
                },
                "localpart": {
                    "type": "string"
                },
                "pgp_fingerprint": {
                    "type": "string"
                },
                "pgp_public_key": {
                    "type": "string"
                },
                "quota_bytes": {
                    "type": "integer"
                },
                "quota_bytes_used": {
                    "type": "integer"
                },
                "reply_body": {
                    "type": "string"
                },
                "reply_enabled": {
                    "type": "boolean"
                },
                "reply_enddate": {
                    "type": "string"
                },
                "reply_startdate": {
                    "type": "string"
                },
                "reply_subject": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "spam_enabled": {
                    "type": "boolean"
                },
                "spam_mark_as_read": {
                    "type": "boolean"
                },
                "spam_threshold": {
                    "type": "integer"
                },
                "totp_enabled": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "whitelist": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_mail.Address": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "mailez_backend_internal_mail.Attachment": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "mailez_backend_internal_mail.Message": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mailez_backend_internal_mail.Attachment"
                    }
                },
                "cc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mailez_backend_internal_mail.Address"
                    }
                },
                "date": {
                    "type": "string"
                },
                "flags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "folder": {
                    "type": "string"
                },
                "from": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mailez_backend_internal_mail.Address"
                    }
                },
                "has_attachment": {
                    "type": "boolean"
                },
                "html_body": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "subject": {
                    "type": "string"
                },
                "text_body": {
                    "type": "string"
                },
                "thread_count": {
                    "type": "integer"
                },
                "thread_id": {
                    "type": "string"
                },
                "thread_latest": {
                    "type": "boolean"
                },
                "to": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mailez_backend_internal_mail.Address"
                    }
                },
                "uid": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "SessionCookie": {
            "type": "apiKey",
            "name": "mailez_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "mailez API",
	Description:      "Self-hosted mail platform — REST API for the admin console and webmail.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
